[build]
  command = "npm run build"
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"
  AT_API_KEY = "@at_api_key"
  AT_USERNAME = "@at_username"
  SENDGRID_API_KEY = "@sendgrid_api_key"

[context.production.environment]
  GCLOUD_PROJECT = "greenet-restaurant"